// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: apikeys.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countApiKeyByUserID = `-- name: CountApiKeyByUserID :one
SELECT
    COUNT(*)
FROM
    apikeys
WHERE
    apikeys.user_id = $1 :: uuid
`

func (q *Queries) CountApiKeyByUserID(ctx context.Context, userid pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countApiKeyByUserID, userid)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertApiKey = `-- name: InsertApiKey :exec
INSERT INTO
    apikeys (
        apikey_id,
        key_hash,
        user_id,
        plain_suffix,
        expired_at
    )
VALUES
    (
        $1,
        $2,
        $3,
        $4,
        $5
    )
`

type InsertApiKeyParams struct {
	ApikeyID       pgtype.UUID        `json:"apikey_id"`
	KeyHash        string             `json:"key_hash"`
	UserID         pgtype.UUID        `json:"user_id"`
	KeyPlainSuffix string             `json:"key_plain_suffix"`
	ExpiredAt      pgtype.Timestamptz `json:"expired_at"`
}

func (q *Queries) InsertApiKey(ctx context.Context, arg InsertApiKeyParams) error {
	_, err := q.db.Exec(ctx, insertApiKey,
		arg.ApikeyID,
		arg.KeyHash,
		arg.UserID,
		arg.KeyPlainSuffix,
		arg.ExpiredAt,
	)
	return err
}
