// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Author struct {
	AuthorID  pgtype.UUID        `json:"author_id"`
	Name      string             `json:"name"`
	Profile   string             `json:"profile"`
	CreatedAt pgtype.Timestamptz `json:"_created_at"`
	UpdatedAt pgtype.Timestamptz `json:"_updated_at"`
}

type Category struct {
	CategoryID pgtype.UUID        `json:"category_id"`
	Name       string             `json:"name"`
	Path       string             `json:"path"`
	CreatedAt  pgtype.Timestamptz `json:"_created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"_updated_at"`
}

type Course struct {
	CourseID    pgtype.UUID `json:"course_id"`
	Title       string      `json:"title"`
	Description string      `json:"description"`
	Slug        string      `json:"slug"`
	Tags        []byte      `json:"tags"`
	// draft / published / archived
	PublishStatus string             `json:"publish_status"`
	CategoryID    pgtype.UUID        `json:"category_id"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
	AuthorID      pgtype.UUID        `json:"author_id"`
	// private = 自分のみ, public = 誰でも閲覧可, paid = 購入者のみ
	Visibility string             `json:"visibility"`
	CreatedAt  pgtype.Timestamptz `json:"_created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"_updated_at"`
}
