// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUser = `-- name: GetUser :one
SELECT
    user_id,
    nickname,
    introduce
FROM
    users
WHERE
    users.user_id = $1 :: UUID
`

type GetUserRow struct {
	UserID    pgtype.UUID `json:"user_id"`
	Nickname  string      `json:"nickname"`
	Introduce string      `json:"introduce"`
}

func (q *Queries) GetUser(ctx context.Context, userid pgtype.UUID) (GetUserRow, error) {
	row := q.db.QueryRow(ctx, getUser, userid)
	var i GetUserRow
	err := row.Scan(&i.UserID, &i.Nickname, &i.Introduce)
	return i, err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE
    users
SET
    nickname = $1,
    introduce = $2
WHERE
    users.user_id = $3 :: UUID
`

type UpdateUserParams struct {
	Nickname  string      `json:"nickname"`
	Introduce string      `json:"introduce"`
	Userid    pgtype.UUID `json:"userid"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser, arg.Nickname, arg.Introduce, arg.Userid)
	return err
}
